# Generated by Django 3.0.4 on 2020-03-31 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('diary', '0001_initial'), ('diary', '0002_auto_20200322_0429'), ('diary', '0003_diary_title')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(verbose_name='user created')),
                ('updated_at', models.DateTimeField(verbose_name='user updated')),
                ('level', models.IntegerField(default=0)),
                ('exp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='diary created')),
                ('content', models.CharField(max_length=2000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.User')),
                ('title', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
