# Generated by Django 3.0.4 on 2020-03-22 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
